"use client"

import { Sidebar } from "@/components/layout/sidebar"
import { DashboardHeader } from "@/components/dashboard/dashboard-header"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { BarChart3, ShieldCheck, AlertTriangle, FileText, Download, RotateCcw, Calendar, CheckCircle } from "lucide-react"
import { toast } from "sonner"
import { useState } from "react"

const reportCategories = [
    {
        title: "Operational Audits",
        count: 12,
        lastUpdated: "2 days ago",
        status: "Compliant",
        icon: ShieldCheck,
        color: "text-green-500",
    },
    {
        title: "Safety Compliance",
        count: 5,
        lastUpdated: "5 hours ago",
        status: "Warning",
        icon: AlertTriangle,
        color: "text-yellow-500",
    },
    {
        title: "Certification Logs",
        count: 48,
        lastUpdated: "1 week ago",
        status: "Compliant",
        icon: FileText,
        color: "text-primary",
    },
    {
        title: "Performance Metrics",
        count: 156,
        lastUpdated: "Just now",
        status: "Compliant",
        icon: BarChart3,
        color: "text-accent",
    },
]

const recentReports = [
    { id: "REP-001", name: "Quarterly Safety Audit", date: "Jan 15, 2026", type: "PDF", size: "2.4 MB" },
    { id: "REP-002", name: "Field Operability Review", date: "Jan 12, 2026", type: "CSV", size: "1.2 MB" },
    { id: "REP-003", name: "AI Accuracy Assessment", date: "Jan 10, 2026", type: "PDF", size: "3.1 MB" },
    { id: "REP-004", name: "Regulatory Compliance Log", date: "Jan 08, 2026", type: "XLSX", size: "850 KB" },
]

const automatedTasks = [
    { name: "Nightly Sync Audit", schedule: "Daily at 02:00", lastRun: "6h ago", status: "Success" },
    { name: "Safety Violation Scan", schedule: "Hourly", lastRun: "12m ago", status: "Success" },
    { name: "Weekly Compliance Rollup", schedule: "Mondays at 00:00", lastRun: "5d ago", status: "Success" },
]

export default function ReportsPage() {
    const [isSidebarOpen, setIsSidebarOpen] = useState(false)
    const [isGenerating, setIsGenerating] = useState(false)
    const [selectedDateRange, setSelectedDateRange] = useState("Last 7 Days")
    const [selectedReportType, setSelectedReportType] = useState("Operational Audit")

    const generateReportContent = (reportType: string, dateRange: string) => {
        const timestamp = new Date().toISOString().split('T')[0]
        const reportData = `
${reportType.toUpperCase()} REPORT
Generated: ${new Date().toLocaleString()}
Date Range: ${dateRange}

EXECUTIVE SUMMARY
================
This ${reportType.toLowerCase()} covers the period of ${dateRange.toLowerCase()}.

KEY FINDINGS
============
• All systems operating within normal parameters
• No critical safety violations detected
• Compliance standards met across all monitored categories
• Performance metrics exceed baseline requirements by 12%

DETAILED METRICS
===============
Total Inspections Conducted: 45
Passed Inspections: 43
Minor Issues Identified: 2
Critical Issues: 0
Average Response Time: 2.3 hours
Compliance Score: 98.5%

RECOMMENDATIONS
==============
1. Continue current monitoring protocols
2. Schedule follow-up inspection for minor issues
3. Update documentation for recent procedure changes
4. Conduct quarterly staff training review

NEXT STEPS
==========
• Follow-up inspection scheduled for Feb 15, 2026
• Monthly compliance review meeting on Feb 1, 2026
• Documentation update due by Feb 10, 2026

---
Report ID: REP-${Math.floor(Math.random() * 1000).toString().padStart(3, '0')}
Generated by: Automated Compliance System
Classification: Internal Use Only
        `.trim()
        
        return reportData
    }

    const handleGenerateReport = async () => {
        setIsGenerating(true)
        
        // Show loading toast
        const loadingToast = toast.loading("Generating report...", {
            description: `Creating ${selectedReportType} for ${selectedDateRange}`
        })

        // Simulate report generation delay
        setTimeout(() => {
            try {
                // Generate report content
                const reportContent = generateReportContent(selectedReportType, selectedDateRange)
                
                // Create blob and download
                const blob = new Blob([reportContent], { type: 'text/plain' })
                const url = window.URL.createObjectURL(blob)
                const link = document.createElement('a')
                
                const timestamp = new Date().toISOString().split('T')[0]
                const fileName = `${selectedReportType.toLowerCase().replace(/\s+/g, '_')}_${timestamp}.txt`
                
                link.href = url
                link.download = fileName
                document.body.appendChild(link)
                link.click()
                document.body.removeChild(link)
                window.URL.revokeObjectURL(url)
                
                // Dismiss loading toast and show success
                toast.dismiss(loadingToast)
                toast.success("Report generated successfully!", {
                    description: `Downloaded: ${fileName}`
                })
            } catch (error) {
                toast.dismiss(loadingToast)
                toast.error("Failed to generate report", {
                    description: "Please try again or contact support"
                })
            } finally {
                setIsGenerating(false)
            }
        }, 1500)
    }

    const handleDownload = (reportName: string) => {
        // Create a sample report for existing reports
        const reportContent = `
${reportName.toUpperCase()}
Downloaded: ${new Date().toLocaleString()}

This is a historical report from the archive.
For demonstration purposes, this contains sample data.

To view the full report, please access the document management system.
        `.trim()
        
        const blob = new Blob([reportContent], { type: 'text/plain' })
        const url = window.URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href = url
        link.download = `${reportName.toLowerCase().replace(/\s+/g, '_')}.txt`
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
        window.URL.revokeObjectURL(url)
        
        toast.success(`Downloaded: ${reportName}`)
    }

    return (
        <div className="flex h-screen bg-background overflow-hidden">
            {/* Mobile overlay */}
            {isSidebarOpen && (
                <div
                    className="fixed inset-0 bg-black/50 md:hidden z-30"
                    onClick={() => setIsSidebarOpen(false)}
                />
            )}
            <Sidebar currentPage="reports & compliance" isOpen={isSidebarOpen} onClose={() => setIsSidebarOpen(false)} />
            <div className="flex-1 flex flex-col overflow-hidden">
                <DashboardHeader onMenuClick={() => setIsSidebarOpen(!isSidebarOpen)} />
                <main className="flex-1 overflow-y-auto p-3 sm:p-4 md:p-6 lg:p-8 max-w-7xl mx-auto w-full">
                    {/* Header Section - Fully Responsive */}
                    <div className="flex flex-col gap-3 sm:gap-4 mb-6 sm:mb-8">
                        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                            <div className="flex-1">
                                <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold text-foreground mb-1 sm:mb-2">
                                    Reports & Compliance
                                </h1>
                                <p className="text-muted-foreground text-xs sm:text-sm">
                                    Automated regulatory tracking and performance audits
                                </p>
                            </div>
                            <div className="flex items-center">
                                <Badge className="bg-primary/10 text-primary border-primary/20 flex gap-1.5 items-center px-2.5 py-1 text-xs sm:text-sm whitespace-nowrap">
                                    <RotateCcw className="w-3 h-3 animate-spin-slow" />
                                    <span className="hidden xs:inline sm:inline">Live Automation Active</span>
                                    <span className="xs:hidden sm:hidden">Active</span>
                                </Badge>
                            </div>
                        </div>
                    </div>

                    {/* Stats Cards - Fully Responsive Grid */}
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 md:gap-6 mb-6 sm:mb-8">
                        {reportCategories.map((cat) => (
                            <Card key={cat.title} className="bg-card/50 backdrop-blur-sm border-sidebar-border hover:shadow-lg transition-all">
                                <CardHeader className="flex flex-row items-center justify-between pb-2 p-3 sm:p-4">
                                    <CardTitle className="text-xs sm:text-sm font-medium text-muted-foreground leading-tight">
                                        {cat.title}
                                    </CardTitle>
                                    <cat.icon className={`h-3.5 w-3.5 sm:h-4 sm:w-4 ${cat.color} flex-shrink-0`} />
                                </CardHeader>
                                <CardContent className="p-3 sm:p-4 pt-0">
                                    <div className="text-xl sm:text-2xl font-bold">{cat.count}</div>
                                    <div className="mt-2 flex items-center justify-between gap-1">
                                        <span className="text-[9px] sm:text-[10px] text-muted-foreground truncate">
                                            {cat.lastUpdated}
                                        </span>
                                        <span className={`text-[9px] sm:text-[10px] font-semibold px-1.5 sm:px-2 py-0.5 rounded-full whitespace-nowrap ${
                                            cat.status === "Compliant" 
                                                ? "bg-green-500/10 text-green-500" 
                                                : "bg-yellow-500/10 text-yellow-500"
                                        }`}>
                                            {cat.status}
                                        </span>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>

                    {/* Automated Dashboard & Manual Request - Responsive Layout */}
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 mb-6 sm:mb-8">
                        {/* Automated Tasks - Takes 2 columns on large screens */}
                        <Card className="lg:col-span-2 bg-card/50 backdrop-blur-sm border-sidebar-border">
                            <CardHeader className="p-4 sm:p-6">
                                <CardTitle className="text-base sm:text-lg">Automated Reporting Dashboard</CardTitle>
                                <CardDescription className="text-xs sm:text-sm">
                                    Scheduled data extraction and compliance checks
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="p-4 sm:p-6 pt-0">
                                <div className="space-y-3 sm:space-y-4">
                                    {automatedTasks.map((task, i) => (
                                        <div key={i} className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 p-3 sm:p-4 rounded-xl bg-sidebar-accent/20 border border-sidebar-border/30">
                                            <div className="flex items-center gap-3 sm:gap-4 min-w-0">
                                                <div className="w-8 h-8 sm:w-10 sm:h-10 rounded bg-background flex items-center justify-center border border-sidebar-border flex-shrink-0">
                                                    <Calendar className="w-4 h-4 sm:w-5 sm:h-5 text-primary" />
                                                </div>
                                                <div className="min-w-0 flex-1">
                                                    <h4 className="font-semibold text-xs sm:text-sm truncate">{task.name}</h4>
                                                    <p className="text-[10px] sm:text-xs text-muted-foreground truncate">
                                                        Schedule: {task.schedule}
                                                    </p>
                                                </div>
                                            </div>
                                            <div className="flex items-center justify-between sm:justify-end gap-3 sm:gap-6 ml-11 sm:ml-0">
                                                <div className="text-left sm:text-right">
                                                    <p className="text-[10px] sm:text-xs text-muted-foreground">Last run</p>
                                                    <p className="text-[10px] sm:text-xs font-bold text-foreground">{task.lastRun}</p>
                                                </div>
                                                <div className="flex items-center gap-1 sm:gap-1.5 text-green-500">
                                                    <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 flex-shrink-0" />
                                                    <span className="text-[10px] sm:text-xs font-bold uppercase tracking-wider whitespace-nowrap">
                                                        {task.status}
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </CardContent>
                        </Card>

                        {/* Manual Request Card - Responsive */}
                        <Card className="bg-card/50 backdrop-blur-sm border-sidebar-border border-dashed">
                            <CardHeader className="p-4 sm:p-6">
                                <CardTitle className="text-base sm:text-lg">Manual Data Request</CardTitle>
                                <CardDescription className="text-xs sm:text-sm">
                                    Instant export for internal audits
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-3 sm:space-y-4 p-4 sm:p-6 pt-0">
                                <div className="space-y-2">
                                    <label className="text-xs font-medium text-muted-foreground">Data Range</label>
                                    <select 
                                        value={selectedDateRange}
                                        onChange={(e) => setSelectedDateRange(e.target.value)}
                                        className="w-full bg-background border border-sidebar-border rounded-md px-3 py-2 text-xs sm:text-sm focus:outline-none focus:ring-1 focus:ring-primary"
                                    >
                                        <option>Last 7 Days</option>
                                        <option>Last 30 Days</option>
                                        <option>Last 90 Days</option>
                                        <option>Custom Range</option>
                                    </select>
                                </div>
                                <div className="space-y-2">
                                    <label className="text-xs font-medium text-muted-foreground">Report Type</label>
                                    <select 
                                        value={selectedReportType}
                                        onChange={(e) => setSelectedReportType(e.target.value)}
                                        className="w-full bg-background border border-sidebar-border rounded-md px-3 py-2 text-xs sm:text-sm focus:outline-none focus:ring-1 focus:ring-primary"
                                    >
                                        <option>Operational Audit</option>
                                        <option>Safety Compliance</option>
                                        <option>Certification Log</option>
                                        <option>Performance Metrics</option>
                                    </select>
                                </div>
                                <button 
                                    onClick={handleGenerateReport} 
                                    disabled={isGenerating}
                                    className="w-full py-2.5 bg-primary text-primary-foreground rounded-md text-xs sm:text-sm font-semibold hover:bg-primary/90 transition-all mt-3 sm:mt-4 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2" 
                                    type="button"
                                >
                                    {isGenerating ? (
                                        <>
                                            <RotateCcw className="w-3.5 h-3.5 sm:w-4 sm:h-4 animate-spin" />
                                            <span>Generating...</span>
                                        </>
                                    ) : (
                                        <>
                                            <Download className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                                            <span>Request Generation</span>
                                        </>
                                    )}
                                </button>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Recent Reports - Fully Responsive Grid */}
                    <Card className="bg-card/50 backdrop-blur-sm border-sidebar-border">
                        <CardHeader className="p-4 sm:p-6">
                            <CardTitle className="text-base sm:text-lg">Recent Generated Reports</CardTitle>
                            <CardDescription className="text-xs sm:text-sm">
                                Archive of system-generated logs
                            </CardDescription>
                        </CardHeader>
                        <CardContent className="p-4 sm:p-6 pt-0">
                            <div className="grid gap-3 sm:gap-4 grid-cols-1 md:grid-cols-2">
                                {recentReports.map((report) => (
                                    <div 
                                        key={report.id} 
                                        className="flex items-center justify-between p-3 sm:p-4 rounded-lg bg-sidebar-accent/30 hover:bg-sidebar-accent/50 transition-colors group border border-sidebar-border/50"
                                    >
                                        <div className="flex items-center gap-3 sm:gap-4 min-w-0 flex-1">
                                            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded bg-background flex items-center justify-center border border-sidebar-border text-muted-foreground group-hover:text-primary transition-colors flex-shrink-0">
                                                <FileText className="w-4 h-4 sm:w-5 sm:h-5" />
                                            </div>
                                            <div className="min-w-0 flex-1">
                                                <h4 className="font-medium text-xs sm:text-sm truncate">{report.name}</h4>
                                                <p className="text-[10px] sm:text-xs text-muted-foreground truncate">
                                                    {report.id} • {report.date}
                                                </p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2 sm:gap-4 flex-shrink-0 ml-2">
                                            <span className="text-[10px] sm:text-xs font-mono text-muted-foreground hidden lg:inline whitespace-nowrap">
                                                {report.type} • {report.size}
                                            </span>
                                            <button 
                                                onClick={() => handleDownload(report.name)} 
                                                className="p-1.5 sm:p-2 hover:bg-primary/20 hover:text-primary rounded-full transition-all flex-shrink-0" 
                                                type="button"
                                                aria-label={`Download ${report.name}`}
                                            >
                                                <Download className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </CardContent>
                    </Card>
                </main>
            </div>
        </div>
    )
}